### ISSUE TITLE
Error in open.connection(x, "rb") : HTTP error 503.

### ISSUE THREAD

**Issue by werkstattcodes** [akshaynagpal/RgScholar#1]
Hi,

any help with the issue below?

```
query_1 <- google_Scholar("heart rate")

[1] "Query URL generated: https://scholar.google.co.in/scholar?as_vis=1&hl=en&num=20&q=heart+rate"
Error in open.connection(x, "rb") : HTTP error 503.
```

many thanks. r

**Comment by akshaynagpal** [comment]
This can happen when you send too many requests from the same IP address to scholar API. Hope this helps.

**Comment by estedeahora** [comment]
I have a similar problem but with a single query. When I use the address directly it works but I need a captcha.

```
library(RgScholar)
query_1 <- google_Scholar("heart rate")
[1] "Query URL generated: https://scholar.google.co.in/scholar?as_vis=1&hl=en&num=20&q=heart+rate"
Error in open.connection(x, "rb") : HTTP error 429.
```

**Comment by MohammadTaghizadeh** [comment]
I also got the same error. It's a very good package but it seems that google does not allow it to work.
